const commands = {
    ALL_SKIN: 'all-skins',
    ARCHITECT: 'arch',
    ARENA: 'arena',
    ARENABYPASS: 'byparena',
    BAN: 'ban',
    B_CROWN_KIT: 'crownkit',
    BOOST: 'boost',
    CUST_ALL: 'set-all',
    CLEARINV: 'clear-inv',
    FREEZE: 'freeze',
    GIVE: 'g',
    GIVE_TO_ALL: 'gta',
    GM: 'gm',
    GLITCH: 'glitch',
    HEAL: 'heal',
    ID: 'id',
    INV: 'see-inv',
    INVISIBLE: 'invis',
    JANITOR: 'janitor',
    KICK: 'kick',
    KICK_ALL: 'kick-all',
    KILL: 'kill',
    MESSAGE_ALL: 'msg',
    POS: 'pos',
    REM_ADMIN: 'rem-admin',
    SERVER_DESC: 'desc',
    SETADMIN: 'admin',
    SETACC: 'set-acc',
    SETBAG: 'set-bag',
    SETBOOK: 'set-book',
    SETBOX: 'set-box',
    SETCODE: 'set-code',
    SETDBOX: 'set-dead',
    SETKILLS: 'set-kills',
    SETLVL: 'set-lvl',
    SETSKIN: 'set-skin',
    SPEED: 'speed',
    STEAL: 'steal',
    TELEPORT: 'tp',
    TELE_TO: 'tpt',
    TO_TELE: 'ttm',
    TP_ALL: 'tpa',
    UNBAN: 'unban',
    UNFREEZE: 'unfreeze',
  };
  
  module.exports = { commands };